# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest' # '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Dockerize App
  jobs:
  - job: Job-1
    displayName: Docker Build and push
    pool:
      name: Default
      # vmImage: ubuntu-latest
    steps:

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'docker-registry'
        repository: 'abubakarriaz/blogi-backend'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: $(tag)

- stage: deploy
  displayName: Deploy to VM
  jobs:
  - job: Job-1
    displayName: SSH and docker container up
    pool:
      name: Default
    steps:

    - task: SSH@0
      inputs:
        sshEndpoint: 'ssh-vm'
        runOptions: 'commands'
        commands: 'docker run -d -p 8100:80 --name blogi-backend-server-01 abubakarriaz/blogi-backend:latest'
        readyTimeout: '20000'
